/**
 * Mandatory Sign-off Utility for MineTech Outbound System
 * Ensures all emails generated by Claude AI, templates, or sent by MineTech
 * end with the standard company signature:
 * "Regards,
 * MineTech Outbound"
 */

export const SIGNATURE_TEXT = 'Regards,\nMineTech Outbound';
export const SIGNATURE_HTML = '<p>Regards,<br/>MineTech Outbound</p>';

const SIGNATURE_REGEX_TEXT = /(?:Best regards|Regards|Kind regards|Warmly|Sincerely|Cheers|Thanks|Best)[,\s]*\n*(?:\[.*?\]|[A-Za-z\s]+)?$/i;
const SIGNATURE_REGEX_HTML = /<p>\s*(?:Best regards|Regards|Kind regards|Warmly|Sincerely|Cheers|Thanks|Best)[,\s]*(?:<br\s*\/?>|\n|\r)*(?:\[.*?\]|[A-Za-z\s]+)?\s*<\/p>\s*$/i;

/**
 * Ensures plain text body ends with "Regards,\nMineTech Outbound"
 */
export function ensureMineTechSignatureText(text = '') {
  if (!text || typeof text !== 'string') {
    return SIGNATURE_TEXT;
  }

  let cleaned = text.trim();

  // If it already ends with MineTech Outbound (with or without comma), return normalized
  if (/MineTech\s+Outbound[\s.]*$/i.test(cleaned)) {
    cleaned = cleaned.replace(/(?:Regards|Best regards|Kind regards)[,\s]*\n*MineTech\s+Outbound[\s.]*$/i, '').trim();
    return `${cleaned}\n\n${SIGNATURE_TEXT}`;
  }

  // If there's an existing placeholder signature at the end (e.g. "Best regards,\nAlex" or "Best,\n[Your Name]")
  if (SIGNATURE_REGEX_TEXT.test(cleaned)) {
    cleaned = cleaned.replace(SIGNATURE_REGEX_TEXT, '').trim();
  }

  return `${cleaned}\n\n${SIGNATURE_TEXT}`;
}

/**
 * Ensures HTML body ends with "<p>Regards,<br/>MineTech Outbound</p>"
 */
export function ensureMineTechSignatureHtml(html = '') {
  if (!html || typeof html !== 'string') {
    return SIGNATURE_HTML;
  }

  let cleaned = html.trim();

  // If HTML already ends with MineTech Outbound
  if (/MineTech\s+Outbound[\s.]*(?:<\/p>|<\/div>)?$/i.test(cleaned)) {
    return cleaned;
  }

  // If there's a trailing sign-off paragraph, replace it
  if (SIGNATURE_REGEX_HTML.test(cleaned)) {
    return cleaned.replace(SIGNATURE_REGEX_HTML, SIGNATURE_HTML);
  }

  return `${cleaned}\n${SIGNATURE_HTML}`;
}

export default {
  SIGNATURE_TEXT,
  SIGNATURE_HTML,
  ensureMineTechSignatureText,
  ensureMineTechSignatureHtml,
};
